Don't write the mirrorlist if it can't be downloaded
Before if the ‘curl’ command failed, it wouldn't send any output to sed, which
would succeed, and that would go into the destination file.

Now we check the status explicitly before moving on and print a message when
‘curl’ fails.

diff --git a/update-mirrors b/update-mirrors
--- a/update-mirrors
+++ b/update-mirrors
@@ -65,8 +65,14 @@ sudo." | fold >&2
 fi
 
 # Download, ready, output
-curl -s -L "$(make-url)" | sed 's/^#\([^#].*\)/\1/' > "$dest"
-echo "Saved in ${dest}"
+mirrorlist=$(curl -s -L "$(make-url)")
+
+if [[ $? -eq 0 ]]; then
+    echo "$mirrorlist" | sed 's/^#\([^#].*\)/\1/' > "$dest"
+    echo "Saved in ${dest}"
+else
+    echo "Couldn't load mirrorlist, not updating."
+fi
 
 if [[ -f "${dest}.pacnew" ]]; then
     rm "${dest}.pacnew"
